In [5]:
import numpy as np

In [7]:
lst = [1,2,3,4]
arr = np.array(lst)

In [8]:
type(arr)

numpy.ndarray

In [9]:
lst1 = [1,2,3,4]
lst2 = [2,3,4,5]
lst3 = [3,4,5,6]

arr1 = np.array([lst1,lst2,lst3])

In [10]:
print(arr1)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [12]:
arr1.shape

(3, 4)

In [13]:
#indexing 
arr

array([1, 2, 3, 4])

In [14]:
arr[3]

4

In [15]:
arr[3]=5

In [16]:
arr

array([1, 2, 3, 5])

In [17]:
arr[1:3]

array([2, 3])

In [19]:
arr[:-1]

array([1, 2, 3])

In [20]:
#reversig the element 
arr[::-1]

array([5, 3, 2, 1])

In [21]:
#jump between two number
arr[::-2]

array([5, 2])

In [22]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [23]:
arr1[:,1]

array([2, 3, 4])

In [24]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [35]:
arr1[ : , 2:]

array([[3, 4],
       [4, 5],
       [5, 6]])

In [36]:
arr<2

array([ True, False, False, False])

In [37]:
arr[arr<2]

array([1])

In [39]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

In [40]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [42]:
arr*arr

array([ 1,  4,  9, 25])

In [45]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.random.randint(10,50,4)

array([12, 45, 13, 15])

In [52]:
np.random.randint(10,50,4).reshape(2,2)

array([[13, 17],
       [19, 34]])

In [53]:
np.random.random_sample((4,7))

array([[0.71943995, 0.49118061, 0.7682334 , 0.80520656, 0.9137165 ,
        0.69549605, 0.47792524],
       [0.16742476, 0.02435746, 0.40610501, 0.87963029, 0.85107663,
        0.14534623, 0.93717158],
       [0.87250697, 0.28415792, 0.23495809, 0.36359731, 0.45673897,
        0.4124354 , 0.88577936],
       [0.79674004, 0.24275486, 0.07059604, 0.72139642, 0.24047626,
        0.08411634, 0.94693566]])

In [1]:
import numpy as np

# Creating a one-dimensional array
one_dim_array = np.array([1, 2, 3, 4, 5])

# Calculating mean, mode, median, and standard deviation
mean = np.mean(one_dim_array)
# Mode - NumPy doesn't have a direct function for mode. You might need to implement it yourself or use other libraries.
median = np.median(one_dim_array)
std_dev = np.std(one_dim_array)

print("One-dimensional array:")
print("Array:", one_dim_array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


One-dimensional array:
Array: [1 2 3 4 5]
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [2]:
# Creating a two-dimensional array
two_dim_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculating mean, median, and standard deviation
mean = np.mean(two_dim_array)
median = np.median(two_dim_array)
std_dev = np.std(two_dim_array)

print("\nTwo-dimensional array:")
print("Array:")
print(two_dim_array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)



Two-dimensional array:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611


In [4]:
# Creating a three-dimensional array
three_dim_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Calculating mean, median, and standard deviation
mean = np.mean(three_dim_array)
median = np.median(three_dim_array)
std_dev = np.std(three_dim_array)

print("\nThree-dimensional array:")
print("Array:")
print(three_dim_array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)




Three-dimensional array:
Array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Mean: 6.5
Median: 6.5
Standard Deviation: 3.452052529534663
